import HeaderItem from "../../../components/HeaderItem";
import Head from "next/head";
import { ArrowLeftIcon } from "@heroicons/react/24/outline";
import Link from "next/link";
import MainInfo from "../../../components/MainInfo";
import { AnimatePresence } from "framer-motion";

const index = ({ movie }) => {
  return (
    <AnimatePresence exitBeforeEnter>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/icon-512x512.png" />
      </Head>
      <Link href={"/"} className="p-4">
        <HeaderItem title="back" Icon={ArrowLeftIcon} />
      </Link>
      <MainInfo movie={movie} />
    </AnimatePresence>
  );
};

export default index;

export const getServerSideProps = async (context) => {
  const res = await fetch(
    `https://api.themoviedb.org/3/movie/${context.params.id}?api_key=7ee8353ee99349e4763fac695eeb02dc`
  );

  const movie = await res.json();

  return {
    props: {
      movie,
    },
  };
};
