import Head from "next/head";
import Header from "../components/Header";
import Navbar from "../components/Navbar";
import Result from "../components/Result";
import request from "../utils/request";
import { motion } from "framer-motion";

export default function Home({ movies }) {
  return (
    <motion.div
      exit={{
        opacity: 0,
      }}
    >
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icons/icon-512x512.png" />
      </Head>
      {/* HEADER */}
      <Header />
      {/* NAVBAR */}
      <Navbar />
      {/* RESULTS */}
      <Result movies={movies} />
    </motion.div>
  );
}

export const getServerSideProps = async (context) => {
  const genre = context.query.genre;
  const res = await fetch(
    `https://api.themoviedb.org/3/${
      request[genre]?.url || request.fetchTrending.url
    }`
  );

  const movies = await res.json();

  return {
    props: {
      movies,
    },
  };
};
